/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiPublicBootstrapDemoRouteImport } from './routes/api/public/bootstrap-demo'
import { Route as AppTenantsResourcesRouteImport } from './routes/_app.tenants.resources'
import { Route as AppTenantsListRouteImport } from './routes/_app.tenants.list'
import { Route as AppTasksTemplatesRouteImport } from './routes/_app.tasks.templates'
import { Route as AppTasksListRouteImport } from './routes/_app.tasks.list'
import { Route as AppTasksDiagnosticsRouteImport } from './routes/_app.tasks.diagnostics'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app.tasks.$taskId'
import { Route as AppTagsListRouteImport } from './routes/_app.tags.list'
import { Route as AppSystemUsersRouteImport } from './routes/_app.system.users'
import { Route as AppSystemRolesRouteImport } from './routes/_app.system.roles'
import { Route as AppSystemModelsRouteImport } from './routes/_app.system.models'
import { Route as AppSystemMenusRouteImport } from './routes/_app.system.menus'
import { Route as AppSystemAiPresetsRouteImport } from './routes/_app.system.ai-presets'
import { Route as AppResourcesIpsRouteImport } from './routes/_app.resources.ips'
import { Route as AppResourcesImagesRouteImport } from './routes/_app.resources.images'
import { Route as AppResourcesDevicesRouteImport } from './routes/_app.resources.devices'
import { Route as AppMaterialsPostsRouteImport } from './routes/_app.materials.posts'
import { Route as AppBillingPlansRouteImport } from './routes/_app.billing.plans'
import { Route as AppBillingDiscountsRouteImport } from './routes/_app.billing.discounts'
import { Route as AppAiVideoRouteImport } from './routes/_app.ai.video'
import { Route as AppAiReplicateRouteImport } from './routes/_app.ai.replicate'
import { Route as AppAiRemixRouteImport } from './routes/_app.ai.remix'
import { Route as AppAiMaterialsRouteImport } from './routes/_app.ai.materials'
import { Route as AppAiLibraryRouteImport } from './routes/_app.ai.library'
import { Route as AppAiImageRouteImport } from './routes/_app.ai.image'
import { Route as AppAiEraseRouteImport } from './routes/_app.ai.erase'
import { Route as AppAgentsWorkspaceRouteImport } from './routes/_app.agents.workspace'
import { Route as AppAgentsModelsRouteImport } from './routes/_app.agents.models'
import { Route as AppAgentsListRouteImport } from './routes/_app.agents.list'
import { Route as AppAccountsMessagesRouteImport } from './routes/_app.accounts.messages'
import { Route as AppAccountsHealthRouteImport } from './routes/_app.accounts.health'
import { Route as AppAccountsFriendsRouteImport } from './routes/_app.accounts.friends'
import { Route as AppAccountsManagedIndexRouteImport } from './routes/_app.accounts.managed.index'
import { Route as AppAccountsManagedIdRouteImport } from './routes/_app.accounts.managed.$id'
import { Route as AppTasksTaskIdLogsIndexRouteImport } from './routes/_app.tasks.$taskId_.logs.index'
import { Route as AppTasksTaskIdLogsLogIdRouteImport } from './routes/_app.tasks.$taskId_.logs.$logId'
import { Route as AppTasksTaskIdLogsSubSubIdRouteImport } from './routes/_app.tasks.$taskId_.logs.sub.$subId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicBootstrapDemoRoute = ApiPublicBootstrapDemoRouteImport.update({
  id: '/api/public/bootstrap-demo',
  path: '/api/public/bootstrap-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTenantsResourcesRoute = AppTenantsResourcesRouteImport.update({
  id: '/tenants/resources',
  path: '/tenants/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsListRoute = AppTenantsListRouteImport.update({
  id: '/tenants/list',
  path: '/tenants/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTemplatesRoute = AppTasksTemplatesRouteImport.update({
  id: '/tasks/templates',
  path: '/tasks/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/tasks/list',
  path: '/tasks/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksDiagnosticsRoute = AppTasksDiagnosticsRouteImport.update({
  id: '/tasks/diagnostics',
  path: '/tasks/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsListRoute = AppTagsListRouteImport.update({
  id: '/tags/list',
  path: '/tags/list',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemUsersRoute = AppSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRolesRoute = AppSystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemModelsRoute = AppSystemModelsRouteImport.update({
  id: '/system/models',
  path: '/system/models',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemMenusRoute = AppSystemMenusRouteImport.update({
  id: '/system/menus',
  path: '/system/menus',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemAiPresetsRoute = AppSystemAiPresetsRouteImport.update({
  id: '/system/ai-presets',
  path: '/system/ai-presets',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesIpsRoute = AppResourcesIpsRouteImport.update({
  id: '/resources/ips',
  path: '/resources/ips',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesImagesRoute = AppResourcesImagesRouteImport.update({
  id: '/resources/images',
  path: '/resources/images',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesDevicesRoute = AppResourcesDevicesRouteImport.update({
  id: '/resources/devices',
  path: '/resources/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsPostsRoute = AppMaterialsPostsRouteImport.update({
  id: '/materials/posts',
  path: '/materials/posts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingPlansRoute = AppBillingPlansRouteImport.update({
  id: '/billing/plans',
  path: '/billing/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingDiscountsRoute = AppBillingDiscountsRouteImport.update({
  id: '/billing/discounts',
  path: '/billing/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiVideoRoute = AppAiVideoRouteImport.update({
  id: '/ai/video',
  path: '/ai/video',
  getParentRoute: () => AppRoute,
} as any)
const AppAiReplicateRoute = AppAiReplicateRouteImport.update({
  id: '/ai/replicate',
  path: '/ai/replicate',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRemixRoute = AppAiRemixRouteImport.update({
  id: '/ai/remix',
  path: '/ai/remix',
  getParentRoute: () => AppRoute,
} as any)
const AppAiMaterialsRoute = AppAiMaterialsRouteImport.update({
  id: '/ai/materials',
  path: '/ai/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppAiLibraryRoute = AppAiLibraryRouteImport.update({
  id: '/ai/library',
  path: '/ai/library',
  getParentRoute: () => AppRoute,
} as any)
const AppAiImageRoute = AppAiImageRouteImport.update({
  id: '/ai/image',
  path: '/ai/image',
  getParentRoute: () => AppRoute,
} as any)
const AppAiEraseRoute = AppAiEraseRouteImport.update({
  id: '/ai/erase',
  path: '/ai/erase',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsWorkspaceRoute = AppAgentsWorkspaceRouteImport.update({
  id: '/agents/workspace',
  path: '/agents/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsModelsRoute = AppAgentsModelsRouteImport.update({
  id: '/agents/models',
  path: '/agents/models',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsListRoute = AppAgentsListRouteImport.update({
  id: '/agents/list',
  path: '/agents/list',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsMessagesRoute = AppAccountsMessagesRouteImport.update({
  id: '/accounts/messages',
  path: '/accounts/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsHealthRoute = AppAccountsHealthRouteImport.update({
  id: '/accounts/health',
  path: '/accounts/health',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsFriendsRoute = AppAccountsFriendsRouteImport.update({
  id: '/accounts/friends',
  path: '/accounts/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsManagedIndexRoute = AppAccountsManagedIndexRouteImport.update({
  id: '/accounts/managed/',
  path: '/accounts/managed/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsManagedIdRoute = AppAccountsManagedIdRouteImport.update({
  id: '/accounts/managed/$id',
  path: '/accounts/managed/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsIndexRoute = AppTasksTaskIdLogsIndexRouteImport.update({
  id: '/tasks/$taskId_/logs/',
  path: '/tasks/$taskId/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsLogIdRoute = AppTasksTaskIdLogsLogIdRouteImport.update({
  id: '/tasks/$taskId_/logs/$logId',
  path: '/tasks/$taskId/logs/$logId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdLogsSubSubIdRoute =
  AppTasksTaskIdLogsSubSubIdRouteImport.update({
    id: '/tasks/$taskId_/logs/sub/$subId',
    path: '/tasks/$taskId/logs/sub/$subId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts/friends': typeof AppAccountsFriendsRoute
  '/accounts/health': typeof AppAccountsHealthRoute
  '/accounts/messages': typeof AppAccountsMessagesRoute
  '/agents/list': typeof AppAgentsListRoute
  '/agents/models': typeof AppAgentsModelsRoute
  '/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/ai/erase': typeof AppAiEraseRoute
  '/ai/image': typeof AppAiImageRoute
  '/ai/library': typeof AppAiLibraryRoute
  '/ai/materials': typeof AppAiMaterialsRoute
  '/ai/remix': typeof AppAiRemixRoute
  '/ai/replicate': typeof AppAiReplicateRoute
  '/ai/video': typeof AppAiVideoRoute
  '/billing/discounts': typeof AppBillingDiscountsRoute
  '/billing/plans': typeof AppBillingPlansRoute
  '/materials/posts': typeof AppMaterialsPostsRoute
  '/resources/devices': typeof AppResourcesDevicesRoute
  '/resources/images': typeof AppResourcesImagesRoute
  '/resources/ips': typeof AppResourcesIpsRoute
  '/system/ai-presets': typeof AppSystemAiPresetsRoute
  '/system/menus': typeof AppSystemMenusRoute
  '/system/models': typeof AppSystemModelsRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/tags/list': typeof AppTagsListRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/diagnostics': typeof AppTasksDiagnosticsRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tenants/list': typeof AppTenantsListRoute
  '/tenants/resources': typeof AppTenantsResourcesRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
  '/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/accounts/managed/': typeof AppAccountsManagedIndexRoute
  '/tasks/$taskId/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/tasks/$taskId/logs/': typeof AppTasksTaskIdLogsIndexRoute
  '/tasks/$taskId/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AppIndexRoute
  '/accounts/friends': typeof AppAccountsFriendsRoute
  '/accounts/health': typeof AppAccountsHealthRoute
  '/accounts/messages': typeof AppAccountsMessagesRoute
  '/agents/list': typeof AppAgentsListRoute
  '/agents/models': typeof AppAgentsModelsRoute
  '/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/ai/erase': typeof AppAiEraseRoute
  '/ai/image': typeof AppAiImageRoute
  '/ai/library': typeof AppAiLibraryRoute
  '/ai/materials': typeof AppAiMaterialsRoute
  '/ai/remix': typeof AppAiRemixRoute
  '/ai/replicate': typeof AppAiReplicateRoute
  '/ai/video': typeof AppAiVideoRoute
  '/billing/discounts': typeof AppBillingDiscountsRoute
  '/billing/plans': typeof AppBillingPlansRoute
  '/materials/posts': typeof AppMaterialsPostsRoute
  '/resources/devices': typeof AppResourcesDevicesRoute
  '/resources/images': typeof AppResourcesImagesRoute
  '/resources/ips': typeof AppResourcesIpsRoute
  '/system/ai-presets': typeof AppSystemAiPresetsRoute
  '/system/menus': typeof AppSystemMenusRoute
  '/system/models': typeof AppSystemModelsRoute
  '/system/roles': typeof AppSystemRolesRoute
  '/system/users': typeof AppSystemUsersRoute
  '/tags/list': typeof AppTagsListRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/diagnostics': typeof AppTasksDiagnosticsRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tenants/list': typeof AppTenantsListRoute
  '/tenants/resources': typeof AppTenantsResourcesRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
  '/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/accounts/managed': typeof AppAccountsManagedIndexRoute
  '/tasks/$taskId/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/tasks/$taskId/logs': typeof AppTasksTaskIdLogsIndexRoute
  '/tasks/$taskId/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/accounts/friends': typeof AppAccountsFriendsRoute
  '/_app/accounts/health': typeof AppAccountsHealthRoute
  '/_app/accounts/messages': typeof AppAccountsMessagesRoute
  '/_app/agents/list': typeof AppAgentsListRoute
  '/_app/agents/models': typeof AppAgentsModelsRoute
  '/_app/agents/workspace': typeof AppAgentsWorkspaceRoute
  '/_app/ai/erase': typeof AppAiEraseRoute
  '/_app/ai/image': typeof AppAiImageRoute
  '/_app/ai/library': typeof AppAiLibraryRoute
  '/_app/ai/materials': typeof AppAiMaterialsRoute
  '/_app/ai/remix': typeof AppAiRemixRoute
  '/_app/ai/replicate': typeof AppAiReplicateRoute
  '/_app/ai/video': typeof AppAiVideoRoute
  '/_app/billing/discounts': typeof AppBillingDiscountsRoute
  '/_app/billing/plans': typeof AppBillingPlansRoute
  '/_app/materials/posts': typeof AppMaterialsPostsRoute
  '/_app/resources/devices': typeof AppResourcesDevicesRoute
  '/_app/resources/images': typeof AppResourcesImagesRoute
  '/_app/resources/ips': typeof AppResourcesIpsRoute
  '/_app/system/ai-presets': typeof AppSystemAiPresetsRoute
  '/_app/system/menus': typeof AppSystemMenusRoute
  '/_app/system/models': typeof AppSystemModelsRoute
  '/_app/system/roles': typeof AppSystemRolesRoute
  '/_app/system/users': typeof AppSystemUsersRoute
  '/_app/tags/list': typeof AppTagsListRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/diagnostics': typeof AppTasksDiagnosticsRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/templates': typeof AppTasksTemplatesRoute
  '/_app/tenants/list': typeof AppTenantsListRoute
  '/_app/tenants/resources': typeof AppTenantsResourcesRoute
  '/api/public/bootstrap-demo': typeof ApiPublicBootstrapDemoRoute
  '/_app/accounts/managed/$id': typeof AppAccountsManagedIdRoute
  '/_app/accounts/managed/': typeof AppAccountsManagedIndexRoute
  '/_app/tasks/$taskId_/logs/$logId': typeof AppTasksTaskIdLogsLogIdRoute
  '/_app/tasks/$taskId_/logs/': typeof AppTasksTaskIdLogsIndexRoute
  '/_app/tasks/$taskId_/logs/sub/$subId': typeof AppTasksTaskIdLogsSubSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/accounts/friends'
    | '/accounts/health'
    | '/accounts/messages'
    | '/agents/list'
    | '/agents/models'
    | '/agents/workspace'
    | '/ai/erase'
    | '/ai/image'
    | '/ai/library'
    | '/ai/materials'
    | '/ai/remix'
    | '/ai/replicate'
    | '/ai/video'
    | '/billing/discounts'
    | '/billing/plans'
    | '/materials/posts'
    | '/resources/devices'
    | '/resources/images'
    | '/resources/ips'
    | '/system/ai-presets'
    | '/system/menus'
    | '/system/models'
    | '/system/roles'
    | '/system/users'
    | '/tags/list'
    | '/tasks/$taskId'
    | '/tasks/diagnostics'
    | '/tasks/list'
    | '/tasks/templates'
    | '/tenants/list'
    | '/tenants/resources'
    | '/api/public/bootstrap-demo'
    | '/accounts/managed/$id'
    | '/accounts/managed/'
    | '/tasks/$taskId/logs/$logId'
    | '/tasks/$taskId/logs/'
    | '/tasks/$taskId/logs/sub/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/accounts/friends'
    | '/accounts/health'
    | '/accounts/messages'
    | '/agents/list'
    | '/agents/models'
    | '/agents/workspace'
    | '/ai/erase'
    | '/ai/image'
    | '/ai/library'
    | '/ai/materials'
    | '/ai/remix'
    | '/ai/replicate'
    | '/ai/video'
    | '/billing/discounts'
    | '/billing/plans'
    | '/materials/posts'
    | '/resources/devices'
    | '/resources/images'
    | '/resources/ips'
    | '/system/ai-presets'
    | '/system/menus'
    | '/system/models'
    | '/system/roles'
    | '/system/users'
    | '/tags/list'
    | '/tasks/$taskId'
    | '/tasks/diagnostics'
    | '/tasks/list'
    | '/tasks/templates'
    | '/tenants/list'
    | '/tenants/resources'
    | '/api/public/bootstrap-demo'
    | '/accounts/managed/$id'
    | '/accounts/managed'
    | '/tasks/$taskId/logs/$logId'
    | '/tasks/$taskId/logs'
    | '/tasks/$taskId/logs/sub/$subId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/'
    | '/_app/accounts/friends'
    | '/_app/accounts/health'
    | '/_app/accounts/messages'
    | '/_app/agents/list'
    | '/_app/agents/models'
    | '/_app/agents/workspace'
    | '/_app/ai/erase'
    | '/_app/ai/image'
    | '/_app/ai/library'
    | '/_app/ai/materials'
    | '/_app/ai/remix'
    | '/_app/ai/replicate'
    | '/_app/ai/video'
    | '/_app/billing/discounts'
    | '/_app/billing/plans'
    | '/_app/materials/posts'
    | '/_app/resources/devices'
    | '/_app/resources/images'
    | '/_app/resources/ips'
    | '/_app/system/ai-presets'
    | '/_app/system/menus'
    | '/_app/system/models'
    | '/_app/system/roles'
    | '/_app/system/users'
    | '/_app/tags/list'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/diagnostics'
    | '/_app/tasks/list'
    | '/_app/tasks/templates'
    | '/_app/tenants/list'
    | '/_app/tenants/resources'
    | '/api/public/bootstrap-demo'
    | '/_app/accounts/managed/$id'
    | '/_app/accounts/managed/'
    | '/_app/tasks/$taskId_/logs/$logId'
    | '/_app/tasks/$taskId_/logs/'
    | '/_app/tasks/$taskId_/logs/sub/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicBootstrapDemoRoute: typeof ApiPublicBootstrapDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/bootstrap-demo': {
      id: '/api/public/bootstrap-demo'
      path: '/api/public/bootstrap-demo'
      fullPath: '/api/public/bootstrap-demo'
      preLoaderRoute: typeof ApiPublicBootstrapDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tenants/resources': {
      id: '/_app/tenants/resources'
      path: '/tenants/resources'
      fullPath: '/tenants/resources'
      preLoaderRoute: typeof AppTenantsResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tenants/list': {
      id: '/_app/tenants/list'
      path: '/tenants/list'
      fullPath: '/tenants/list'
      preLoaderRoute: typeof AppTenantsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/templates': {
      id: '/_app/tasks/templates'
      path: '/tasks/templates'
      fullPath: '/tasks/templates'
      preLoaderRoute: typeof AppTasksTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/tasks/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/diagnostics': {
      id: '/_app/tasks/diagnostics'
      path: '/tasks/diagnostics'
      fullPath: '/tasks/diagnostics'
      preLoaderRoute: typeof AppTasksDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags/list': {
      id: '/_app/tags/list'
      path: '/tags/list'
      fullPath: '/tags/list'
      preLoaderRoute: typeof AppTagsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/users': {
      id: '/_app/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof AppSystemUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/roles': {
      id: '/_app/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof AppSystemRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/models': {
      id: '/_app/system/models'
      path: '/system/models'
      fullPath: '/system/models'
      preLoaderRoute: typeof AppSystemModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/menus': {
      id: '/_app/system/menus'
      path: '/system/menus'
      fullPath: '/system/menus'
      preLoaderRoute: typeof AppSystemMenusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/ai-presets': {
      id: '/_app/system/ai-presets'
      path: '/system/ai-presets'
      fullPath: '/system/ai-presets'
      preLoaderRoute: typeof AppSystemAiPresetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/ips': {
      id: '/_app/resources/ips'
      path: '/resources/ips'
      fullPath: '/resources/ips'
      preLoaderRoute: typeof AppResourcesIpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/images': {
      id: '/_app/resources/images'
      path: '/resources/images'
      fullPath: '/resources/images'
      preLoaderRoute: typeof AppResourcesImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources/devices': {
      id: '/_app/resources/devices'
      path: '/resources/devices'
      fullPath: '/resources/devices'
      preLoaderRoute: typeof AppResourcesDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials/posts': {
      id: '/_app/materials/posts'
      path: '/materials/posts'
      fullPath: '/materials/posts'
      preLoaderRoute: typeof AppMaterialsPostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/plans': {
      id: '/_app/billing/plans'
      path: '/billing/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof AppBillingPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/discounts': {
      id: '/_app/billing/discounts'
      path: '/billing/discounts'
      fullPath: '/billing/discounts'
      preLoaderRoute: typeof AppBillingDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/video': {
      id: '/_app/ai/video'
      path: '/ai/video'
      fullPath: '/ai/video'
      preLoaderRoute: typeof AppAiVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/replicate': {
      id: '/_app/ai/replicate'
      path: '/ai/replicate'
      fullPath: '/ai/replicate'
      preLoaderRoute: typeof AppAiReplicateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/remix': {
      id: '/_app/ai/remix'
      path: '/ai/remix'
      fullPath: '/ai/remix'
      preLoaderRoute: typeof AppAiRemixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/materials': {
      id: '/_app/ai/materials'
      path: '/ai/materials'
      fullPath: '/ai/materials'
      preLoaderRoute: typeof AppAiMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/library': {
      id: '/_app/ai/library'
      path: '/ai/library'
      fullPath: '/ai/library'
      preLoaderRoute: typeof AppAiLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/image': {
      id: '/_app/ai/image'
      path: '/ai/image'
      fullPath: '/ai/image'
      preLoaderRoute: typeof AppAiImageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai/erase': {
      id: '/_app/ai/erase'
      path: '/ai/erase'
      fullPath: '/ai/erase'
      preLoaderRoute: typeof AppAiEraseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/workspace': {
      id: '/_app/agents/workspace'
      path: '/agents/workspace'
      fullPath: '/agents/workspace'
      preLoaderRoute: typeof AppAgentsWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/models': {
      id: '/_app/agents/models'
      path: '/agents/models'
      fullPath: '/agents/models'
      preLoaderRoute: typeof AppAgentsModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/list': {
      id: '/_app/agents/list'
      path: '/agents/list'
      fullPath: '/agents/list'
      preLoaderRoute: typeof AppAgentsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/messages': {
      id: '/_app/accounts/messages'
      path: '/accounts/messages'
      fullPath: '/accounts/messages'
      preLoaderRoute: typeof AppAccountsMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/health': {
      id: '/_app/accounts/health'
      path: '/accounts/health'
      fullPath: '/accounts/health'
      preLoaderRoute: typeof AppAccountsHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/friends': {
      id: '/_app/accounts/friends'
      path: '/accounts/friends'
      fullPath: '/accounts/friends'
      preLoaderRoute: typeof AppAccountsFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/managed/': {
      id: '/_app/accounts/managed/'
      path: '/accounts/managed'
      fullPath: '/accounts/managed/'
      preLoaderRoute: typeof AppAccountsManagedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/managed/$id': {
      id: '/_app/accounts/managed/$id'
      path: '/accounts/managed/$id'
      fullPath: '/accounts/managed/$id'
      preLoaderRoute: typeof AppAccountsManagedIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/': {
      id: '/_app/tasks/$taskId_/logs/'
      path: '/tasks/$taskId/logs'
      fullPath: '/tasks/$taskId/logs/'
      preLoaderRoute: typeof AppTasksTaskIdLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/$logId': {
      id: '/_app/tasks/$taskId_/logs/$logId'
      path: '/tasks/$taskId/logs/$logId'
      fullPath: '/tasks/$taskId/logs/$logId'
      preLoaderRoute: typeof AppTasksTaskIdLogsLogIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId_/logs/sub/$subId': {
      id: '/_app/tasks/$taskId_/logs/sub/$subId'
      path: '/tasks/$taskId/logs/sub/$subId'
      fullPath: '/tasks/$taskId/logs/sub/$subId'
      preLoaderRoute: typeof AppTasksTaskIdLogsSubSubIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountsFriendsRoute: typeof AppAccountsFriendsRoute
  AppAccountsHealthRoute: typeof AppAccountsHealthRoute
  AppAccountsMessagesRoute: typeof AppAccountsMessagesRoute
  AppAgentsListRoute: typeof AppAgentsListRoute
  AppAgentsModelsRoute: typeof AppAgentsModelsRoute
  AppAgentsWorkspaceRoute: typeof AppAgentsWorkspaceRoute
  AppAiEraseRoute: typeof AppAiEraseRoute
  AppAiImageRoute: typeof AppAiImageRoute
  AppAiLibraryRoute: typeof AppAiLibraryRoute
  AppAiMaterialsRoute: typeof AppAiMaterialsRoute
  AppAiRemixRoute: typeof AppAiRemixRoute
  AppAiReplicateRoute: typeof AppAiReplicateRoute
  AppAiVideoRoute: typeof AppAiVideoRoute
  AppBillingDiscountsRoute: typeof AppBillingDiscountsRoute
  AppBillingPlansRoute: typeof AppBillingPlansRoute
  AppMaterialsPostsRoute: typeof AppMaterialsPostsRoute
  AppResourcesDevicesRoute: typeof AppResourcesDevicesRoute
  AppResourcesImagesRoute: typeof AppResourcesImagesRoute
  AppResourcesIpsRoute: typeof AppResourcesIpsRoute
  AppSystemAiPresetsRoute: typeof AppSystemAiPresetsRoute
  AppSystemMenusRoute: typeof AppSystemMenusRoute
  AppSystemModelsRoute: typeof AppSystemModelsRoute
  AppSystemRolesRoute: typeof AppSystemRolesRoute
  AppSystemUsersRoute: typeof AppSystemUsersRoute
  AppTagsListRoute: typeof AppTagsListRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksDiagnosticsRoute: typeof AppTasksDiagnosticsRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksTemplatesRoute: typeof AppTasksTemplatesRoute
  AppTenantsListRoute: typeof AppTenantsListRoute
  AppTenantsResourcesRoute: typeof AppTenantsResourcesRoute
  AppAccountsManagedIdRoute: typeof AppAccountsManagedIdRoute
  AppAccountsManagedIndexRoute: typeof AppAccountsManagedIndexRoute
  AppTasksTaskIdLogsLogIdRoute: typeof AppTasksTaskIdLogsLogIdRoute
  AppTasksTaskIdLogsIndexRoute: typeof AppTasksTaskIdLogsIndexRoute
  AppTasksTaskIdLogsSubSubIdRoute: typeof AppTasksTaskIdLogsSubSubIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountsFriendsRoute: AppAccountsFriendsRoute,
  AppAccountsHealthRoute: AppAccountsHealthRoute,
  AppAccountsMessagesRoute: AppAccountsMessagesRoute,
  AppAgentsListRoute: AppAgentsListRoute,
  AppAgentsModelsRoute: AppAgentsModelsRoute,
  AppAgentsWorkspaceRoute: AppAgentsWorkspaceRoute,
  AppAiEraseRoute: AppAiEraseRoute,
  AppAiImageRoute: AppAiImageRoute,
  AppAiLibraryRoute: AppAiLibraryRoute,
  AppAiMaterialsRoute: AppAiMaterialsRoute,
  AppAiRemixRoute: AppAiRemixRoute,
  AppAiReplicateRoute: AppAiReplicateRoute,
  AppAiVideoRoute: AppAiVideoRoute,
  AppBillingDiscountsRoute: AppBillingDiscountsRoute,
  AppBillingPlansRoute: AppBillingPlansRoute,
  AppMaterialsPostsRoute: AppMaterialsPostsRoute,
  AppResourcesDevicesRoute: AppResourcesDevicesRoute,
  AppResourcesImagesRoute: AppResourcesImagesRoute,
  AppResourcesIpsRoute: AppResourcesIpsRoute,
  AppSystemAiPresetsRoute: AppSystemAiPresetsRoute,
  AppSystemMenusRoute: AppSystemMenusRoute,
  AppSystemModelsRoute: AppSystemModelsRoute,
  AppSystemRolesRoute: AppSystemRolesRoute,
  AppSystemUsersRoute: AppSystemUsersRoute,
  AppTagsListRoute: AppTagsListRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksDiagnosticsRoute: AppTasksDiagnosticsRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksTemplatesRoute: AppTasksTemplatesRoute,
  AppTenantsListRoute: AppTenantsListRoute,
  AppTenantsResourcesRoute: AppTenantsResourcesRoute,
  AppAccountsManagedIdRoute: AppAccountsManagedIdRoute,
  AppAccountsManagedIndexRoute: AppAccountsManagedIndexRoute,
  AppTasksTaskIdLogsLogIdRoute: AppTasksTaskIdLogsLogIdRoute,
  AppTasksTaskIdLogsIndexRoute: AppTasksTaskIdLogsIndexRoute,
  AppTasksTaskIdLogsSubSubIdRoute: AppTasksTaskIdLogsSubSubIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicBootstrapDemoRoute: ApiPublicBootstrapDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
